language: node_js
node_js:
  - "8.1.2"

os:
  # - linux
  - osx

env:
  - CC=clang CXX=clang
  - CC=gcc-4.8 CXX=g++-4.8

matrix:
    exclude:
    - os: osx
      env: CC=gcc-4.8 CXX=g++-4.8
    - os: linux
      env: CC=clang CXX=clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      
before_script:
  - g++ -v
  - npm install -g node-gyp@latest
  - node-gyp -v
  